require 'ffi-compiler/compile_task'

FFI::Compiler::CompileTask.new('random') do |c|
  c.cflags << "-O3 -march=native"
  # c.have_header?('stdio.h', '/usr/local/include')
  # c.have_func?('puts')
  # c.have_library?('z')
end
